using System.Globalization;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;

namespace JYPPX.OpenCvSharp.Tools.ManagedApiBaseline;

internal static class Program
{
    private const string TargetFramework = "net8.0";
    private static readonly NullabilityInfoContext Nullability = new();
    private static readonly StringComparer Ordinal = StringComparer.Ordinal;

    public static int Main(string[] args)
    {
        try
        {
            var options = Options.Parse(args);
            var assembly = typeof(JYPPX.OpenCvSharp.Core.Cv2).Assembly;
            var result = Generate(assembly);

            WriteOrCheck(options.OutputPath, result.Baseline, options.Check);
            WriteOrCheck(options.SummaryPath, result.Summary, options.Check);

            Console.WriteLine(
                $"MANAGED_API_BASELINE_OK assembly={assembly.GetName().Name} " +
                $"types={result.TypeCount} members={result.MemberCount} " +
                $"namespaces={result.NamespaceCount} sha256={result.BaselineSha256} " +
                $"mode={(options.Check ? "check" : "write")}");
            return 0;
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine(ex.Message);
            return 1;
        }
    }

    private static GenerationResult Generate(Assembly assembly)
    {
        var types = assembly.GetTypes()
            .Where(IsApiVisibleType)
            .Where(type => !IsCompilerGenerated(type))
            .OrderBy(FormatTypeIdentity, Ordinal)
            .ToArray();

        var typeLines = new List<string>();
        var memberLines = new List<string>();
        var namespaceCounts = new SortedDictionary<string, NamespaceCount>(Ordinal);

        foreach (var type in types)
        {
            var owner = FormatTypeIdentity(type);
            typeLines.Add(FormatTypeDeclaration(type));

            var namespaceName = type.Namespace ?? "<global>";
            if (!namespaceCounts.TryGetValue(namespaceName, out var count))
            {
                count = new NamespaceCount();
                namespaceCounts.Add(namespaceName, count);
            }

            count.TypeCount++;
            foreach (var memberLine in GetMemberLines(type, owner))
            {
                memberLines.Add(memberLine);
                count.MemberCount++;
            }
        }

        typeLines.Sort(Ordinal);
        memberLines.Sort(Ordinal);

        var baselineLines = new List<string>
        {
            "# Generated by tools/ManagedApiBaseline. Do not edit.",
            "schema-version=1",
            $"assembly={assembly.GetName().Name}",
            $"target-framework={TargetFramework}",
            $"type-count={typeLines.Count}",
            $"member-count={memberLines.Count}",
            $"namespace-count={namespaceCounts.Count}",
            "nullable-shape=included",
            string.Empty,
            "[types]"
        };
        baselineLines.AddRange(typeLines);
        baselineLines.Add(string.Empty);
        baselineLines.Add("[members]");
        baselineLines.AddRange(memberLines);

        var baseline = string.Join('\n', baselineLines) + "\n";
        var baselineSha256 = Convert.ToHexString(
            SHA256.HashData(new UTF8Encoding(false).GetBytes(baseline))).ToLowerInvariant();

        var summaryModel = new
        {
            schemaVersion = 1,
            generator = "tools/ManagedApiBaseline",
            assemblyName = assembly.GetName().Name,
            targetFramework = TargetFramework,
            nullableShape = "included",
            typeCount = typeLines.Count,
            memberCount = memberLines.Count,
            namespaceCount = namespaceCounts.Count,
            baselinePath = "compatibility/managed-public-api.txt",
            baselineSha256,
            namespaces = namespaceCounts.Select(pair => new
            {
                name = pair.Key,
                typeCount = pair.Value.TypeCount,
                memberCount = pair.Value.MemberCount
            }).ToArray()
        };
        var summary = NormalizeNewLines(JsonSerializer.Serialize(
            summaryModel,
            new JsonSerializerOptions { WriteIndented = true })) + "\n";

        return new GenerationResult(
            baseline,
            summary,
            typeLines.Count,
            memberLines.Count,
            namespaceCounts.Count,
            baselineSha256);
    }

    private static IEnumerable<string> GetMemberLines(Type type, string owner)
    {
        const BindingFlags flags = BindingFlags.DeclaredOnly |
                                   BindingFlags.Instance |
                                   BindingFlags.Static |
                                   BindingFlags.Public |
                                   BindingFlags.NonPublic;

        foreach (var constructor in type.GetConstructors(flags)
                     .Where(IsApiVisibleMethod)
                     .Where(method => !IsCompilerGenerated(method)))
        {
            yield return $"MEMBER|{owner}|constructor|{FormatMethodModifiers(constructor)}|" +
                         $".ctor({FormatParameters(constructor.GetParameters())})";
        }

        foreach (var method in type.GetMethods(flags)
                     .Where(IsApiVisibleMethod)
                     .Where(method => !IsCompilerGenerated(method))
                     .Where(method => !IsPropertyOrEventAccessor(method)))
        {
            var nullability = TryGetNullability(method.ReturnParameter);
            var returnType = FormatType(method.ReturnType, nullability);
            var genericArguments = method.IsGenericMethodDefinition
                ? $"<{string.Join(',', method.GetGenericArguments().Select(argument => argument.Name))}>"
                : string.Empty;
            var constraints = FormatGenericConstraints(method.GetGenericArguments());
            yield return $"MEMBER|{owner}|method|{FormatMethodModifiers(method)}|" +
                         $"{returnType} {method.Name}{genericArguments}" +
                         $"({FormatParameters(method.GetParameters())}){constraints}";
        }

        foreach (var property in type.GetProperties(flags).Where(IsApiVisibleProperty))
        {
            var accessors = new List<string>();
            if (property.GetMethod is not null && IsApiVisibleMethod(property.GetMethod))
            {
                accessors.Add($"get:{FormatAccessibility(property.GetMethod)}");
            }

            if (property.SetMethod is not null && IsApiVisibleMethod(property.SetMethod))
            {
                var kind = property.SetMethod.ReturnParameter.GetRequiredCustomModifiers()
                    .Any(modifier => modifier == typeof(IsExternalInit))
                    ? "init"
                    : "set";
                accessors.Add($"{kind}:{FormatAccessibility(property.SetMethod)}");
            }

            var staticModifier = IsStatic(property) ? "static" : "instance";
            var propertyType = FormatType(property.PropertyType, TryGetNullability(property));
            var indexParameters = property.GetIndexParameters();
            var indexer = indexParameters.Length == 0
                ? string.Empty
                : $"[{FormatParameters(indexParameters)}]";
            yield return $"MEMBER|{owner}|property|{staticModifier};{string.Join(';', accessors)}|" +
                         $"{propertyType} {property.Name}{indexer}";
        }

        foreach (var eventInfo in type.GetEvents(flags).Where(IsApiVisibleEvent))
        {
            var accessors = new List<string>();
            if (eventInfo.AddMethod is not null && IsApiVisibleMethod(eventInfo.AddMethod))
            {
                accessors.Add($"add:{FormatAccessibility(eventInfo.AddMethod)}");
            }

            if (eventInfo.RemoveMethod is not null && IsApiVisibleMethod(eventInfo.RemoveMethod))
            {
                accessors.Add($"remove:{FormatAccessibility(eventInfo.RemoveMethod)}");
            }

            var eventType = eventInfo.EventHandlerType is null
                ? "<unknown>"
                : FormatType(eventInfo.EventHandlerType, TryGetNullability(eventInfo));
            var staticModifier = IsStatic(eventInfo) ? "static" : "instance";
            yield return $"MEMBER|{owner}|event|{staticModifier};{string.Join(';', accessors)}|" +
                         $"{eventType} {eventInfo.Name}";
        }

        foreach (var field in type.GetFields(flags)
                     .Where(IsApiVisibleField)
                     .Where(field => !IsCompilerGenerated(field)))
        {
            var modifiers = new List<string> { FormatAccessibility(field) };
            if (field.IsLiteral)
            {
                modifiers.Add("const");
            }
            else
            {
                modifiers.Add(field.IsStatic ? "static" : "instance");
                if (field.IsInitOnly)
                {
                    modifiers.Add("readonly");
                }
            }

            var value = field.IsLiteral
                ? $"={FormatConstant(field.GetRawConstantValue())}"
                : string.Empty;
            yield return $"MEMBER|{owner}|field|{string.Join(';', modifiers)}|" +
                         $"{FormatType(field.FieldType, TryGetNullability(field))} {field.Name}{value}";
        }
    }

    private static string FormatTypeDeclaration(Type type)
    {
        var modifiers = new List<string> { FormatAccessibility(type) };
        if (type.IsAbstract && type.IsSealed)
        {
            modifiers.Add("static");
        }
        else
        {
            if (type.IsAbstract && !type.IsInterface)
            {
                modifiers.Add("abstract");
            }

            if (type.IsSealed && !type.IsValueType)
            {
                modifiers.Add("sealed");
            }
        }

        if (type.IsValueType && HasAttribute(type, "System.Runtime.CompilerServices.IsReadOnlyAttribute"))
        {
            modifiers.Add("readonly");
        }

        if (type.IsByRefLike)
        {
            modifiers.Add("ref-like");
        }

        var kind = GetTypeKind(type);
        var baseType = type.BaseType is null || type.BaseType == typeof(object) ||
                       type.BaseType == typeof(ValueType) || type.BaseType == typeof(Enum) ||
                       type.BaseType == typeof(MulticastDelegate)
            ? string.Empty
            : FormatType(type.BaseType, null);
        var interfaces = type.GetInterfaces()
            .Select(interfaceType => FormatType(interfaceType, null))
            .OrderBy(value => value, Ordinal)
            .ToArray();
        var constraints = FormatGenericConstraints(type.GetGenericArguments());

        return $"TYPE|{kind}|{string.Join(';', modifiers)}|{FormatTypeIdentity(type)}|" +
               $"base={baseType}|interfaces={string.Join(',', interfaces)}{constraints}";
    }

    private static string FormatMethodModifiers(MethodBase method)
    {
        var modifiers = new List<string> { FormatAccessibility(method) };
        modifiers.Add(method.IsStatic ? "static" : "instance");

        if (method.IsAbstract)
        {
            modifiers.Add("abstract");
        }
        else if (method.IsVirtual)
        {
            if (method.IsFinal)
            {
                modifiers.Add("sealed-override");
            }
            else if (method is MethodInfo methodInfo && methodInfo.GetBaseDefinition() != methodInfo)
            {
                modifiers.Add("override");
            }
            else
            {
                modifiers.Add("virtual");
            }
        }

        return string.Join(';', modifiers);
    }

    private static string FormatParameters(IReadOnlyList<ParameterInfo> parameters)
    {
        var parts = new string[parameters.Count];
        for (var index = 0; index < parameters.Count; index++)
        {
            var parameter = parameters[index];
            var modifiers = new List<string>();
            if (parameter.GetCustomAttribute<ParamArrayAttribute>() is not null)
            {
                modifiers.Add("params");
            }

            if (parameter.ParameterType.IsByRef)
            {
                modifiers.Add(parameter.IsOut ? "out" : parameter.IsIn ? "in" : "ref");
            }

            var parameterType = parameter.ParameterType.IsByRef
                ? parameter.ParameterType.GetElementType()!
                : parameter.ParameterType;
            var formattedType = FormatType(parameterType, TryGetNullability(parameter));
            var defaultValue = parameter.HasDefaultValue
                ? $"={FormatConstant(parameter.DefaultValue)}"
                : string.Empty;
            var prefix = modifiers.Count == 0 ? string.Empty : string.Join(' ', modifiers) + " ";
            parts[index] = $"{prefix}{formattedType} {parameter.Name}{defaultValue}";
        }

        return string.Join(',', parts);
    }

    private static string FormatType(Type type, NullabilityInfo? nullability)
    {
        if (type.IsByRef)
        {
            return FormatType(type.GetElementType()!, nullability?.ElementType);
        }

        if (type.IsPointer)
        {
            return FormatType(type.GetElementType()!, nullability?.ElementType) + "*";
        }

        if (type.IsArray)
        {
            var commas = new string(',', type.GetArrayRank() - 1);
            var arrayName = FormatType(type.GetElementType()!, nullability?.ElementType) + $"[{commas}]";
            return AddNullableSuffix(arrayName, type, nullability);
        }

        if (type.IsFunctionPointer)
        {
            var parameterTypes = type.GetFunctionPointerParameterTypes()
                .Select(parameterType => FormatType(parameterType, null));
            var signature = $"delegate*<{string.Join(',', parameterTypes.Append(FormatType(type.GetFunctionPointerReturnType(), null)))}>";
            return signature;
        }

        if (type.IsGenericParameter)
        {
            return AddNullableSuffix(type.Name, type, nullability);
        }

        if (type.IsGenericType && type.GetGenericTypeDefinition() == typeof(Nullable<>))
        {
            var argumentNullability = nullability?.GenericTypeArguments.FirstOrDefault();
            return FormatType(type.GetGenericArguments()[0], argumentNullability) + "?";
        }

        var name = FormatNonGenericTypeName(type);
        var ownArity = GetOwnGenericArity(type);
        if (ownArity > 0)
        {
            var arguments = type.GetGenericArguments();
            var ownArguments = arguments.Skip(arguments.Length - ownArity).ToArray();
            var nullabilityArguments = nullability?.GenericTypeArguments ?? Array.Empty<NullabilityInfo>();
            var ownNullability = nullabilityArguments.Skip(Math.Max(0, nullabilityArguments.Length - ownArity)).ToArray();
            var formattedArguments = ownArguments.Select((argument, index) =>
                FormatType(argument, index < ownNullability.Length ? ownNullability[index] : null));
            name += $"<{string.Join(',', formattedArguments)}>";
        }

        return AddNullableSuffix(name, type, nullability);
    }

    private static string FormatTypeIdentity(Type type) => FormatType(type, null);

    private static string FormatNonGenericTypeName(Type type)
    {
        var simpleName = type.Name.Split('`')[0];
        if (type.IsNested && type.DeclaringType is not null)
        {
            return $"{FormatTypeIdentity(type.DeclaringType)}.{simpleName}";
        }

        return string.IsNullOrEmpty(type.Namespace) ? simpleName : $"{type.Namespace}.{simpleName}";
    }

    private static string AddNullableSuffix(string name, Type type, NullabilityInfo? nullability)
    {
        if ((!type.IsValueType || type.IsGenericParameter) &&
            nullability?.ReadState == NullabilityState.Nullable)
        {
            return name + "?";
        }

        return name;
    }

    private static string FormatGenericConstraints(IReadOnlyList<Type> arguments)
    {
        var genericParameters = arguments.Where(argument => argument.IsGenericParameter)
            .OrderBy(argument => argument.GenericParameterPosition)
            .ToArray();
        if (genericParameters.Length == 0)
        {
            return string.Empty;
        }

        var parts = new List<string>();
        foreach (var parameter in genericParameters)
        {
            var constraints = new List<string>();
            var attributes = parameter.GenericParameterAttributes;
            var variance = attributes & GenericParameterAttributes.VarianceMask;
            if (variance == GenericParameterAttributes.Covariant)
            {
                constraints.Add("covariant");
            }
            else if (variance == GenericParameterAttributes.Contravariant)
            {
                constraints.Add("contravariant");
            }

            var special = attributes & GenericParameterAttributes.SpecialConstraintMask;
            if ((special & GenericParameterAttributes.ReferenceTypeConstraint) != 0)
            {
                constraints.Add("reference-type");
            }

            if ((special & GenericParameterAttributes.NotNullableValueTypeConstraint) != 0)
            {
                constraints.Add("non-nullable-value-type");
            }

            foreach (var constraint in parameter.GetGenericParameterConstraints()
                         .Select(constraint => FormatType(constraint, null))
                         .OrderBy(value => value, Ordinal))
            {
                constraints.Add(constraint);
            }

            if ((special & GenericParameterAttributes.DefaultConstructorConstraint) != 0)
            {
                constraints.Add("default-constructor");
            }

            parts.Add($"{parameter.Name}:{string.Join('&', constraints)}");
        }

        return $"|generic={string.Join(',', parts)}";
    }

    private static string FormatConstant(object? value)
    {
        if (value is null || value == DBNull.Value || value == Missing.Value)
        {
            return "null";
        }

        return value switch
        {
            string text => JsonSerializer.Serialize(text),
            char character => JsonSerializer.Serialize(character.ToString()),
            bool boolean => boolean ? "true" : "false",
            float single => single.ToString("R", CultureInfo.InvariantCulture),
            double number => number.ToString("R", CultureInfo.InvariantCulture),
            decimal number => number.ToString(CultureInfo.InvariantCulture),
            _ => Convert.ToString(value, CultureInfo.InvariantCulture) ?? string.Empty
        };
    }

    private static bool IsApiVisibleType(Type type)
    {
        if (type.IsNested)
        {
            var ownVisibility = type.IsNestedPublic || type.IsNestedFamily || type.IsNestedFamORAssem;
            return ownVisibility && type.DeclaringType is not null && IsApiVisibleType(type.DeclaringType);
        }

        return type.IsPublic;
    }

    private static bool IsApiVisibleMethod(MethodBase method) =>
        method.IsPublic || method.IsFamily || method.IsFamilyOrAssembly;

    private static bool IsApiVisibleField(FieldInfo field) =>
        field.IsPublic || field.IsFamily || field.IsFamilyOrAssembly;

    private static bool IsApiVisibleProperty(PropertyInfo property) =>
        (property.GetMethod is not null && IsApiVisibleMethod(property.GetMethod)) ||
        (property.SetMethod is not null && IsApiVisibleMethod(property.SetMethod));

    private static bool IsApiVisibleEvent(EventInfo eventInfo) =>
        (eventInfo.AddMethod is not null && IsApiVisibleMethod(eventInfo.AddMethod)) ||
        (eventInfo.RemoveMethod is not null && IsApiVisibleMethod(eventInfo.RemoveMethod));

    private static bool IsPropertyOrEventAccessor(MethodInfo method) =>
        method.IsSpecialName &&
        (method.Name.StartsWith("get_", StringComparison.Ordinal) ||
         method.Name.StartsWith("set_", StringComparison.Ordinal) ||
         method.Name.StartsWith("add_", StringComparison.Ordinal) ||
         method.Name.StartsWith("remove_", StringComparison.Ordinal));

    private static bool IsCompilerGenerated(MemberInfo member) =>
        member.GetCustomAttribute<CompilerGeneratedAttribute>() is not null ||
        member.Name.Contains('<', StringComparison.Ordinal);

    private static bool IsStatic(PropertyInfo property) =>
        property.GetMethod?.IsStatic == true || property.SetMethod?.IsStatic == true;

    private static bool IsStatic(EventInfo eventInfo) =>
        eventInfo.AddMethod?.IsStatic == true || eventInfo.RemoveMethod?.IsStatic == true;

    private static bool HasAttribute(MemberInfo member, string fullName) =>
        member.CustomAttributes.Any(attribute => attribute.AttributeType.FullName == fullName);

    private static string GetTypeKind(Type type)
    {
        if (type.IsEnum) return "enum";
        if (typeof(MulticastDelegate).IsAssignableFrom(type.BaseType)) return "delegate";
        if (type.IsInterface) return "interface";
        if (type.IsValueType) return "struct";
        return "class";
    }

    private static int GetOwnGenericArity(Type type)
    {
        var marker = type.Name.LastIndexOf('`');
        return marker < 0
            ? 0
            : int.Parse(type.Name[(marker + 1)..], CultureInfo.InvariantCulture);
    }

    private static string FormatAccessibility(Type type)
    {
        if (type.IsPublic || type.IsNestedPublic) return "public";
        if (type.IsNestedFamily) return "protected";
        if (type.IsNestedFamORAssem) return "protected-internal";
        return "non-public";
    }

    private static string FormatAccessibility(MethodBase method)
    {
        if (method.IsPublic) return "public";
        if (method.IsFamily) return "protected";
        if (method.IsFamilyOrAssembly) return "protected-internal";
        return "non-public";
    }

    private static string FormatAccessibility(FieldInfo field)
    {
        if (field.IsPublic) return "public";
        if (field.IsFamily) return "protected";
        if (field.IsFamilyOrAssembly) return "protected-internal";
        return "non-public";
    }

    private static NullabilityInfo? TryGetNullability(ParameterInfo parameter)
    {
        try { return Nullability.Create(parameter); }
        catch (InvalidOperationException) { return null; }
    }

    private static NullabilityInfo? TryGetNullability(PropertyInfo property)
    {
        try { return Nullability.Create(property); }
        catch (InvalidOperationException) { return null; }
    }

    private static NullabilityInfo? TryGetNullability(FieldInfo field)
    {
        try { return Nullability.Create(field); }
        catch (InvalidOperationException) { return null; }
    }

    private static NullabilityInfo? TryGetNullability(EventInfo eventInfo)
    {
        try { return Nullability.Create(eventInfo); }
        catch (InvalidOperationException) { return null; }
    }

    private static void WriteOrCheck(string path, string content, bool check)
    {
        var normalized = NormalizeNewLines(content).TrimEnd() + "\n";
        if (check)
        {
            if (!File.Exists(path))
            {
                throw new InvalidOperationException($"Generated file is missing: {path}");
            }

            var current = NormalizeNewLines(File.ReadAllText(path)).TrimEnd() + "\n";
            if (!string.Equals(current, normalized, StringComparison.Ordinal))
            {
                throw new InvalidOperationException($"Generated file is out of date: {path}");
            }

            return;
        }

        Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(path))!);
        File.WriteAllText(path, normalized, new UTF8Encoding(false));
    }

    private static string NormalizeNewLines(string value) =>
        value.Replace("\r\n", "\n", StringComparison.Ordinal)
            .Replace('\r', '\n');

    private sealed class NamespaceCount
    {
        public int TypeCount { get; set; }
        public int MemberCount { get; set; }
    }

    private sealed record GenerationResult(
        string Baseline,
        string Summary,
        int TypeCount,
        int MemberCount,
        int NamespaceCount,
        string BaselineSha256);

    private sealed record Options(string OutputPath, string SummaryPath, bool Check)
    {
        public static Options Parse(IReadOnlyList<string> args)
        {
            string? output = null;
            string? summary = null;
            var check = false;

            for (var index = 0; index < args.Count; index++)
            {
                switch (args[index])
                {
                    case "--output" when index + 1 < args.Count:
                        output = args[++index];
                        break;
                    case "--summary" when index + 1 < args.Count:
                        summary = args[++index];
                        break;
                    case "--check":
                        check = true;
                        break;
                    default:
                        throw new ArgumentException($"Unknown or incomplete argument: {args[index]}");
                }
            }

            if (string.IsNullOrWhiteSpace(output) || string.IsNullOrWhiteSpace(summary))
            {
                throw new ArgumentException("--output and --summary are required.");
            }

            return new Options(Path.GetFullPath(output), Path.GetFullPath(summary), check);
        }
    }
}
