// <auto-generated>
// Generated by scripts/Generate-MatTypeConstants.ps1 from OpenCV 5.0.0 modules/core/include/opencv2/core/hal/interface.h.
// Do not edit this file manually.
// </auto-generated>

namespace OpenCvSharp.Core
{
    /// <summary>
    /// Provides generated OpenCV matrix type constants.
    /// 提供生成的 OpenCV 矩阵类型常量。
    /// </summary>
    public static partial class MatType
    {
        /// <summary>
        /// Maximum supported OpenCV channel count, equivalent to <c>CV_CN_MAX</c>.
        /// OpenCV 支持的最大通道数，等价于 <c>CV_CN_MAX</c>。
        /// </summary>
        public const int ChannelMax = 128;

        /// <summary>
        /// Channel bit shift used by OpenCV matrix type encoding, equivalent to <c>CV_CN_SHIFT</c>.
        /// OpenCV 矩阵类型编码使用的通道位移，等价于 <c>CV_CN_SHIFT</c>。
        /// </summary>
        public const int ChannelShift = 5;

        /// <summary>
        /// Maximum OpenCV depth slot count, equivalent to <c>CV_DEPTH_MAX</c>.
        /// OpenCV 深度槽数量上限，等价于 <c>CV_DEPTH_MAX</c>。
        /// </summary>
        public const int DepthMax = 32;

        /// <summary>
        /// OpenCV matrix depth mask, equivalent to <c>CV_MAT_DEPTH_MASK</c>.
        /// OpenCV 矩阵深度掩码，等价于 <c>CV_MAT_DEPTH_MASK</c>。
        /// </summary>
        public const int DepthMask = 31;

        /// <summary>
        /// OpenCV matrix channel mask, equivalent to <c>CV_MAT_CN_MASK</c>.
        /// OpenCV 矩阵通道掩码，等价于 <c>CV_MAT_CN_MASK</c>。
        /// </summary>
        public const int ChannelMask = 4064;

        /// <summary>
        /// OpenCV matrix type mask, equivalent to <c>CV_MAT_TYPE_MASK</c>.
        /// OpenCV 矩阵类型掩码，等价于 <c>CV_MAT_TYPE_MASK</c>。
        /// </summary>
        public const int MatrixTypeMask = 4095;

        /// <summary>
        /// OpenCV matrix element depth constant, equivalent to <c>CV_8U</c>.
        /// OpenCV 矩阵元素深度常量，等价于 <c>CV_8U</c>。
        /// </summary>
        public const int CV_8U = 0;

        /// <summary>
        /// OpenCV matrix element depth constant, equivalent to <c>CV_8S</c>.
        /// OpenCV 矩阵元素深度常量，等价于 <c>CV_8S</c>。
        /// </summary>
        public const int CV_8S = 1;

        /// <summary>
        /// OpenCV matrix element depth constant, equivalent to <c>CV_16U</c>.
        /// OpenCV 矩阵元素深度常量，等价于 <c>CV_16U</c>。
        /// </summary>
        public const int CV_16U = 2;

        /// <summary>
        /// OpenCV matrix element depth constant, equivalent to <c>CV_16S</c>.
        /// OpenCV 矩阵元素深度常量，等价于 <c>CV_16S</c>。
        /// </summary>
        public const int CV_16S = 3;

        /// <summary>
        /// OpenCV matrix element depth constant, equivalent to <c>CV_32S</c>.
        /// OpenCV 矩阵元素深度常量，等价于 <c>CV_32S</c>。
        /// </summary>
        public const int CV_32S = 4;

        /// <summary>
        /// OpenCV matrix element depth constant, equivalent to <c>CV_32F</c>.
        /// OpenCV 矩阵元素深度常量，等价于 <c>CV_32F</c>。
        /// </summary>
        public const int CV_32F = 5;

        /// <summary>
        /// OpenCV matrix element depth constant, equivalent to <c>CV_64F</c>.
        /// OpenCV 矩阵元素深度常量，等价于 <c>CV_64F</c>。
        /// </summary>
        public const int CV_64F = 6;

        /// <summary>
        /// OpenCV matrix element depth constant, equivalent to <c>CV_16F</c>.
        /// OpenCV 矩阵元素深度常量，等价于 <c>CV_16F</c>。
        /// </summary>
        public const int CV_16F = 7;

        /// <summary>
        /// OpenCV matrix element depth constant, equivalent to <c>CV_16BF</c>.
        /// OpenCV 矩阵元素深度常量，等价于 <c>CV_16BF</c>。
        /// </summary>
        public const int CV_16BF = 8;

        /// <summary>
        /// OpenCV matrix element depth constant, equivalent to <c>CV_Bool</c>.
        /// OpenCV 矩阵元素深度常量，等价于 <c>CV_Bool</c>。
        /// </summary>
        public const int CV_Bool = 9;

        /// <summary>
        /// OpenCV matrix element depth constant, equivalent to <c>CV_64U</c>.
        /// OpenCV 矩阵元素深度常量，等价于 <c>CV_64U</c>。
        /// </summary>
        public const int CV_64U = 10;

        /// <summary>
        /// OpenCV matrix element depth constant, equivalent to <c>CV_64S</c>.
        /// OpenCV 矩阵元素深度常量，等价于 <c>CV_64S</c>。
        /// </summary>
        public const int CV_64S = 11;

        /// <summary>
        /// OpenCV matrix element depth constant, equivalent to <c>CV_32U</c>.
        /// OpenCV 矩阵元素深度常量，等价于 <c>CV_32U</c>。
        /// </summary>
        public const int CV_32U = 12;

        /// <summary>
        /// OpenCV matrix type constant, equivalent to <c>CV_8UC1</c>.
        /// OpenCV 矩阵类型常量，等价于 <c>CV_8UC1</c>。
        /// </summary>
        public const int CV_8UC1 = 0;

        /// <summary>
        /// OpenCV matrix type constant, equivalent to <c>CV_8UC2</c>.
        /// OpenCV 矩阵类型常量，等价于 <c>CV_8UC2</c>。
        /// </summary>
        public const int CV_8UC2 = 32;

        /// <summary>
        /// OpenCV matrix type constant, equivalent to <c>CV_8UC3</c>.
        /// OpenCV 矩阵类型常量，等价于 <c>CV_8UC3</c>。
        /// </summary>
        public const int CV_8UC3 = 64;

        /// <summary>
        /// OpenCV matrix type constant, equivalent to <c>CV_8UC4</c>.
        /// OpenCV 矩阵类型常量，等价于 <c>CV_8UC4</c>。
        /// </summary>
        public const int CV_8UC4 = 96;

        /// <summary>
        /// OpenCV matrix type constant, equivalent to <c>CV_8SC1</c>.
        /// OpenCV 矩阵类型常量，等价于 <c>CV_8SC1</c>。
        /// </summary>
        public const int CV_8SC1 = 1;

        /// <summary>
        /// OpenCV matrix type constant, equivalent to <c>CV_8SC2</c>.
        /// OpenCV 矩阵类型常量，等价于 <c>CV_8SC2</c>。
        /// </summary>
        public const int CV_8SC2 = 33;

        /// <summary>
        /// OpenCV matrix type constant, equivalent to <c>CV_8SC3</c>.
        /// OpenCV 矩阵类型常量，等价于 <c>CV_8SC3</c>。
        /// </summary>
        public const int CV_8SC3 = 65;

        /// <summary>
        /// OpenCV matrix type constant, equivalent to <c>CV_8SC4</c>.
        /// OpenCV 矩阵类型常量，等价于 <c>CV_8SC4</c>。
        /// </summary>
        public const int CV_8SC4 = 97;

        /// <summary>
        /// OpenCV matrix type constant, equivalent to <c>CV_16UC1</c>.
        /// OpenCV 矩阵类型常量，等价于 <c>CV_16UC1</c>。
        /// </summary>
        public const int CV_16UC1 = 2;

        /// <summary>
        /// OpenCV matrix type constant, equivalent to <c>CV_16UC2</c>.
        /// OpenCV 矩阵类型常量，等价于 <c>CV_16UC2</c>。
        /// </summary>
        public const int CV_16UC2 = 34;

        /// <summary>
        /// OpenCV matrix type constant, equivalent to <c>CV_16UC3</c>.
        /// OpenCV 矩阵类型常量，等价于 <c>CV_16UC3</c>。
        /// </summary>
        public const int CV_16UC3 = 66;

        /// <summary>
        /// OpenCV matrix type constant, equivalent to <c>CV_16UC4</c>.
        /// OpenCV 矩阵类型常量，等价于 <c>CV_16UC4</c>。
        /// </summary>
        public const int CV_16UC4 = 98;

        /// <summary>
        /// OpenCV matrix type constant, equivalent to <c>CV_16SC1</c>.
        /// OpenCV 矩阵类型常量，等价于 <c>CV_16SC1</c>。
        /// </summary>
        public const int CV_16SC1 = 3;

        /// <summary>
        /// OpenCV matrix type constant, equivalent to <c>CV_16SC2</c>.
        /// OpenCV 矩阵类型常量，等价于 <c>CV_16SC2</c>。
        /// </summary>
        public const int CV_16SC2 = 35;

        /// <summary>
        /// OpenCV matrix type constant, equivalent to <c>CV_16SC3</c>.
        /// OpenCV 矩阵类型常量，等价于 <c>CV_16SC3</c>。
        /// </summary>
        public const int CV_16SC3 = 67;

        /// <summary>
        /// OpenCV matrix type constant, equivalent to <c>CV_16SC4</c>.
        /// OpenCV 矩阵类型常量，等价于 <c>CV_16SC4</c>。
        /// </summary>
        public const int CV_16SC4 = 99;

        /// <summary>
        /// OpenCV matrix type constant, equivalent to <c>CV_32SC1</c>.
        /// OpenCV 矩阵类型常量，等价于 <c>CV_32SC1</c>。
        /// </summary>
        public const int CV_32SC1 = 4;

        /// <summary>
        /// OpenCV matrix type constant, equivalent to <c>CV_32SC2</c>.
        /// OpenCV 矩阵类型常量，等价于 <c>CV_32SC2</c>。
        /// </summary>
        public const int CV_32SC2 = 36;

        /// <summary>
        /// OpenCV matrix type constant, equivalent to <c>CV_32SC3</c>.
        /// OpenCV 矩阵类型常量，等价于 <c>CV_32SC3</c>。
        /// </summary>
        public const int CV_32SC3 = 68;

        /// <summary>
        /// OpenCV matrix type constant, equivalent to <c>CV_32SC4</c>.
        /// OpenCV 矩阵类型常量，等价于 <c>CV_32SC4</c>。
        /// </summary>
        public const int CV_32SC4 = 100;

        /// <summary>
        /// OpenCV matrix type constant, equivalent to <c>CV_32FC1</c>.
        /// OpenCV 矩阵类型常量，等价于 <c>CV_32FC1</c>。
        /// </summary>
        public const int CV_32FC1 = 5;

        /// <summary>
        /// OpenCV matrix type constant, equivalent to <c>CV_32FC2</c>.
        /// OpenCV 矩阵类型常量，等价于 <c>CV_32FC2</c>。
        /// </summary>
        public const int CV_32FC2 = 37;

        /// <summary>
        /// OpenCV matrix type constant, equivalent to <c>CV_32FC3</c>.
        /// OpenCV 矩阵类型常量，等价于 <c>CV_32FC3</c>。
        /// </summary>
        public const int CV_32FC3 = 69;

        /// <summary>
        /// OpenCV matrix type constant, equivalent to <c>CV_32FC4</c>.
        /// OpenCV 矩阵类型常量，等价于 <c>CV_32FC4</c>。
        /// </summary>
        public const int CV_32FC4 = 101;

        /// <summary>
        /// OpenCV matrix type constant, equivalent to <c>CV_64FC1</c>.
        /// OpenCV 矩阵类型常量，等价于 <c>CV_64FC1</c>。
        /// </summary>
        public const int CV_64FC1 = 6;

        /// <summary>
        /// OpenCV matrix type constant, equivalent to <c>CV_64FC2</c>.
        /// OpenCV 矩阵类型常量，等价于 <c>CV_64FC2</c>。
        /// </summary>
        public const int CV_64FC2 = 38;

        /// <summary>
        /// OpenCV matrix type constant, equivalent to <c>CV_64FC3</c>.
        /// OpenCV 矩阵类型常量，等价于 <c>CV_64FC3</c>。
        /// </summary>
        public const int CV_64FC3 = 70;

        /// <summary>
        /// OpenCV matrix type constant, equivalent to <c>CV_64FC4</c>.
        /// OpenCV 矩阵类型常量，等价于 <c>CV_64FC4</c>。
        /// </summary>
        public const int CV_64FC4 = 102;

        /// <summary>
        /// OpenCV matrix type constant, equivalent to <c>CV_16FC1</c>.
        /// OpenCV 矩阵类型常量，等价于 <c>CV_16FC1</c>。
        /// </summary>
        public const int CV_16FC1 = 7;

        /// <summary>
        /// OpenCV matrix type constant, equivalent to <c>CV_16FC2</c>.
        /// OpenCV 矩阵类型常量，等价于 <c>CV_16FC2</c>。
        /// </summary>
        public const int CV_16FC2 = 39;

        /// <summary>
        /// OpenCV matrix type constant, equivalent to <c>CV_16FC3</c>.
        /// OpenCV 矩阵类型常量，等价于 <c>CV_16FC3</c>。
        /// </summary>
        public const int CV_16FC3 = 71;

        /// <summary>
        /// OpenCV matrix type constant, equivalent to <c>CV_16FC4</c>.
        /// OpenCV 矩阵类型常量，等价于 <c>CV_16FC4</c>。
        /// </summary>
        public const int CV_16FC4 = 103;

        /// <summary>
        /// OpenCV matrix type constant, equivalent to <c>CV_16BFC1</c>.
        /// OpenCV 矩阵类型常量，等价于 <c>CV_16BFC1</c>。
        /// </summary>
        public const int CV_16BFC1 = 8;

        /// <summary>
        /// OpenCV matrix type constant, equivalent to <c>CV_16BFC2</c>.
        /// OpenCV 矩阵类型常量，等价于 <c>CV_16BFC2</c>。
        /// </summary>
        public const int CV_16BFC2 = 40;

        /// <summary>
        /// OpenCV matrix type constant, equivalent to <c>CV_16BFC3</c>.
        /// OpenCV 矩阵类型常量，等价于 <c>CV_16BFC3</c>。
        /// </summary>
        public const int CV_16BFC3 = 72;

        /// <summary>
        /// OpenCV matrix type constant, equivalent to <c>CV_16BFC4</c>.
        /// OpenCV 矩阵类型常量，等价于 <c>CV_16BFC4</c>。
        /// </summary>
        public const int CV_16BFC4 = 104;

        /// <summary>
        /// OpenCV matrix type constant, equivalent to <c>CV_BoolC1</c>.
        /// OpenCV 矩阵类型常量，等价于 <c>CV_BoolC1</c>。
        /// </summary>
        public const int CV_BoolC1 = 9;

        /// <summary>
        /// OpenCV matrix type constant, equivalent to <c>CV_BoolC2</c>.
        /// OpenCV 矩阵类型常量，等价于 <c>CV_BoolC2</c>。
        /// </summary>
        public const int CV_BoolC2 = 41;

        /// <summary>
        /// OpenCV matrix type constant, equivalent to <c>CV_BoolC3</c>.
        /// OpenCV 矩阵类型常量，等价于 <c>CV_BoolC3</c>。
        /// </summary>
        public const int CV_BoolC3 = 73;

        /// <summary>
        /// OpenCV matrix type constant, equivalent to <c>CV_BoolC4</c>.
        /// OpenCV 矩阵类型常量，等价于 <c>CV_BoolC4</c>。
        /// </summary>
        public const int CV_BoolC4 = 105;

        /// <summary>
        /// OpenCV matrix type constant, equivalent to <c>CV_64UC1</c>.
        /// OpenCV 矩阵类型常量，等价于 <c>CV_64UC1</c>。
        /// </summary>
        public const int CV_64UC1 = 10;

        /// <summary>
        /// OpenCV matrix type constant, equivalent to <c>CV_64UC2</c>.
        /// OpenCV 矩阵类型常量，等价于 <c>CV_64UC2</c>。
        /// </summary>
        public const int CV_64UC2 = 42;

        /// <summary>
        /// OpenCV matrix type constant, equivalent to <c>CV_64UC3</c>.
        /// OpenCV 矩阵类型常量，等价于 <c>CV_64UC3</c>。
        /// </summary>
        public const int CV_64UC3 = 74;

        /// <summary>
        /// OpenCV matrix type constant, equivalent to <c>CV_64UC4</c>.
        /// OpenCV 矩阵类型常量，等价于 <c>CV_64UC4</c>。
        /// </summary>
        public const int CV_64UC4 = 106;

        /// <summary>
        /// OpenCV matrix type constant, equivalent to <c>CV_64SC1</c>.
        /// OpenCV 矩阵类型常量，等价于 <c>CV_64SC1</c>。
        /// </summary>
        public const int CV_64SC1 = 11;

        /// <summary>
        /// OpenCV matrix type constant, equivalent to <c>CV_64SC2</c>.
        /// OpenCV 矩阵类型常量，等价于 <c>CV_64SC2</c>。
        /// </summary>
        public const int CV_64SC2 = 43;

        /// <summary>
        /// OpenCV matrix type constant, equivalent to <c>CV_64SC3</c>.
        /// OpenCV 矩阵类型常量，等价于 <c>CV_64SC3</c>。
        /// </summary>
        public const int CV_64SC3 = 75;

        /// <summary>
        /// OpenCV matrix type constant, equivalent to <c>CV_64SC4</c>.
        /// OpenCV 矩阵类型常量，等价于 <c>CV_64SC4</c>。
        /// </summary>
        public const int CV_64SC4 = 107;

        /// <summary>
        /// OpenCV matrix type constant, equivalent to <c>CV_32UC1</c>.
        /// OpenCV 矩阵类型常量，等价于 <c>CV_32UC1</c>。
        /// </summary>
        public const int CV_32UC1 = 12;

        /// <summary>
        /// OpenCV matrix type constant, equivalent to <c>CV_32UC2</c>.
        /// OpenCV 矩阵类型常量，等价于 <c>CV_32UC2</c>。
        /// </summary>
        public const int CV_32UC2 = 44;

        /// <summary>
        /// OpenCV matrix type constant, equivalent to <c>CV_32UC3</c>.
        /// OpenCV 矩阵类型常量，等价于 <c>CV_32UC3</c>。
        /// </summary>
        public const int CV_32UC3 = 76;

        /// <summary>
        /// OpenCV matrix type constant, equivalent to <c>CV_32UC4</c>.
        /// OpenCV 矩阵类型常量，等价于 <c>CV_32UC4</c>。
        /// </summary>
        public const int CV_32UC4 = 108;

    }
}
