#pragma once

#define OPENCV_CSHARP_STATUS_OK 0
#define OPENCV_CSHARP_STATUS_INVALID_ARGUMENT -1
#define OPENCV_CSHARP_STATUS_NULL_POINTER -2
#define OPENCV_CSHARP_STATUS_NOT_LINKED -100
#define OPENCV_CSHARP_STATUS_OUT_OF_MEMORY -1001
#define OPENCV_CSHARP_STATUS_NATIVE_EXCEPTION -1002

#ifndef OPENCV_CSHARP_STATUS_EXCEPTION
#define OPENCV_CSHARP_STATUS_EXCEPTION OPENCV_CSHARP_STATUS_NATIVE_EXCEPTION
#endif
