param(
    [string]$OpenCvVersion = "5.0.0",
    [string]$WorkspaceRoot = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path,
    [string]$OpenCvSourceRoot = "",
    [string]$OutputPath = "",
    [switch]$Check
)

$ErrorActionPreference = "Stop"

$repoRoot = Resolve-Path (Join-Path $PSScriptRoot "..")
function Get-DefaultOpenCvSourceRoot {
    param(
        [Parameter(Mandatory = $true)]
        [string]$WorkspaceRoot,
        [Parameter(Mandatory = $true)]
        [string]$OpenCvVersion
    )

    # Prefer the version-neutral workspace source root when it exists.
    $neutralSourceRoot = Join-Path $WorkspaceRoot "opencv-source"
    if (Test-Path $neutralSourceRoot) {
        return $neutralSourceRoot
    }

    $versionMatch = [regex]::Match($OpenCvVersion, "^(\d+)(?:\.|$)")
    if (-not $versionMatch.Success) {
        throw "OpenCvVersion must start with a numeric major version: $OpenCvVersion"
    }

    # Keep the major-version source directory only as a legacy/current local fallback.
    return Join-Path $WorkspaceRoot "opencv$($versionMatch.Groups[1].Value)-source code"
}

if ([string]::IsNullOrWhiteSpace($OpenCvSourceRoot)) {
    $OpenCvSourceRoot = Get-DefaultOpenCvSourceRoot -WorkspaceRoot $WorkspaceRoot -OpenCvVersion $OpenCvVersion
}

# Upstream OpenCV source leaf directory includes the selected version as factual source artifact identity.
$opencvSource = Join-Path $OpenCvSourceRoot "opencv-$OpenCvVersion"
$interfaceHeader = Join-Path $opencvSource "modules\core\include\opencv2\core\hal\interface.h"

if ([string]::IsNullOrWhiteSpace($OutputPath)) {
    $OutputPath = Join-Path $repoRoot "src\OpenCvSharp\Core\MatType.Generated.cs"
}

if (-not (Test-Path $interfaceHeader)) {
    throw "OpenCV interface header was not found: $interfaceHeader"
}

$lines = Get-Content -LiteralPath $interfaceHeader

function Get-MacroValue {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Name
    )

    $pattern = "^\s*#define\s+$([regex]::Escape($Name))\s+(.+?)\s*$"
    foreach ($line in $lines) {
        $match = [regex]::Match($line, $pattern)
        if ($match.Success) {
            return $match.Groups[1].Value.Trim()
        }
    }

    throw "Macro was not found: $Name"
}

function Convert-ToInt {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Value
    )

    $text = $Value.Trim()
    if ($text -match "^\(?1\s*<<\s*(\d+)\)?$") {
        return [int](1 -shl [int]$matches[1])
    }

    if ($text -match "^\(?([0-9]+)\)?$") {
        return [int]$matches[1]
    }

    throw "Unsupported macro value: $Value"
}

$channelMax = Convert-ToInt (Get-MacroValue "CV_CN_MAX")
$channelShift = Convert-ToInt (Get-MacroValue "CV_CN_SHIFT")
$depthMax = 1 -shl $channelShift
$depthMask = $depthMax - 1
$channelMask = ($channelMax - 1) -shl $channelShift
$matrixTypeMask = ($depthMax * $channelMax) - 1

$depthMacros = New-Object System.Collections.Generic.List[object]
foreach ($line in $lines) {
    $match = [regex]::Match($line, "^\s*#define\s+(CV_(?:8U|8S|16U|16S|32S|32F|64F|16F|16BF|Bool|64U|64S|32U))\s+([0-9]+)\s*$")
    if ($match.Success) {
        $depthMacros.Add([pscustomobject]@{
            Name = $match.Groups[1].Value
            Value = [int]$match.Groups[2].Value
        })
    }
}

if ($depthMacros.Count -eq 0) {
    throw "No OpenCV depth macros were found in $interfaceHeader"
}

$typeMacros = New-Object System.Collections.Generic.List[object]
foreach ($depth in $depthMacros) {
    for ($channels = 1; $channels -le 4; $channels++) {
        $name = "$($depth.Name)C$channels"
        $value = ($depth.Value -band $depthMask) + (($channels - 1) -shl $channelShift)
        $typeMacros.Add([pscustomobject]@{
            Name = $name
            DepthName = $depth.Name
            Channels = $channels
            Value = $value
        })
    }
}

$content = New-Object System.Collections.Generic.List[string]
$content.Add("// <auto-generated>")
$content.Add("// Generated by scripts/Generate-MatTypeConstants.ps1 from OpenCV $OpenCvVersion modules/core/include/opencv2/core/hal/interface.h.")
$content.Add("// Do not edit this file manually.")
$content.Add("// </auto-generated>")
$content.Add("")
$content.Add("namespace OpenCvSharp.Core")
$content.Add("{")
$content.Add("    /// <summary>")
$content.Add("    /// Provides generated OpenCV matrix type constants.")
$content.Add("    /// 提供生成的 OpenCV 矩阵类型常量。")
$content.Add("    /// </summary>")
$content.Add("    public static partial class MatType")
$content.Add("    {")
$content.Add("        /// <summary>")
$content.Add("        /// Maximum supported OpenCV channel count, equivalent to <c>CV_CN_MAX</c>.")
$content.Add("        /// OpenCV 支持的最大通道数，等价于 <c>CV_CN_MAX</c>。")
$content.Add("        /// </summary>")
$content.Add("        public const int ChannelMax = $channelMax;")
$content.Add("")
$content.Add("        /// <summary>")
$content.Add("        /// Channel bit shift used by OpenCV matrix type encoding, equivalent to <c>CV_CN_SHIFT</c>.")
$content.Add("        /// OpenCV 矩阵类型编码使用的通道位移，等价于 <c>CV_CN_SHIFT</c>。")
$content.Add("        /// </summary>")
$content.Add("        public const int ChannelShift = $channelShift;")
$content.Add("")
$content.Add("        /// <summary>")
$content.Add("        /// Maximum OpenCV depth slot count, equivalent to <c>CV_DEPTH_MAX</c>.")
$content.Add("        /// OpenCV 深度槽数量上限，等价于 <c>CV_DEPTH_MAX</c>。")
$content.Add("        /// </summary>")
$content.Add("        public const int DepthMax = $depthMax;")
$content.Add("")
$content.Add("        /// <summary>")
$content.Add("        /// OpenCV matrix depth mask, equivalent to <c>CV_MAT_DEPTH_MASK</c>.")
$content.Add("        /// OpenCV 矩阵深度掩码，等价于 <c>CV_MAT_DEPTH_MASK</c>。")
$content.Add("        /// </summary>")
$content.Add("        public const int DepthMask = $depthMask;")
$content.Add("")
$content.Add("        /// <summary>")
$content.Add("        /// OpenCV matrix channel mask, equivalent to <c>CV_MAT_CN_MASK</c>.")
$content.Add("        /// OpenCV 矩阵通道掩码，等价于 <c>CV_MAT_CN_MASK</c>。")
$content.Add("        /// </summary>")
$content.Add("        public const int ChannelMask = $channelMask;")
$content.Add("")
$content.Add("        /// <summary>")
$content.Add("        /// OpenCV matrix type mask, equivalent to <c>CV_MAT_TYPE_MASK</c>.")
$content.Add("        /// OpenCV 矩阵类型掩码，等价于 <c>CV_MAT_TYPE_MASK</c>。")
$content.Add("        /// </summary>")
$content.Add("        public const int MatrixTypeMask = $matrixTypeMask;")
$content.Add("")

foreach ($depth in $depthMacros) {
    $content.Add("        /// <summary>")
    $content.Add("        /// OpenCV matrix element depth constant, equivalent to <c>$($depth.Name)</c>.")
    $content.Add("        /// OpenCV 矩阵元素深度常量，等价于 <c>$($depth.Name)</c>。")
    $content.Add("        /// </summary>")
    $content.Add("        public const int $($depth.Name) = $($depth.Value);")
    $content.Add("")
}

foreach ($type in $typeMacros) {
    $content.Add("        /// <summary>")
    $content.Add("        /// OpenCV matrix type constant, equivalent to <c>$($type.Name)</c>.")
    $content.Add("        /// OpenCV 矩阵类型常量，等价于 <c>$($type.Name)</c>。")
    $content.Add("        /// </summary>")
    $content.Add("        public const int $($type.Name) = $($type.Value);")
    $content.Add("")
}

$content.Add("    }")
$content.Add("}")

$newContent = ($content -join [Environment]::NewLine) + [Environment]::NewLine

if ($Check) {
    if (-not (Test-Path $OutputPath)) {
        throw "Generated file was not found: $OutputPath"
    }

    $currentContent = [System.IO.File]::ReadAllText($OutputPath, [System.Text.UTF8Encoding]::new($false, $true))
    if ($currentContent -ne $newContent) {
        throw "Generated MatType constants are out of date. Run scripts/Generate-MatTypeConstants.ps1."
    }

    Write-Host "Generated MatType constants are up to date: $OutputPath"
    return
}

$outputDirectory = Split-Path -Parent $OutputPath
New-Item -ItemType Directory -Force $outputDirectory | Out-Null
[System.IO.File]::WriteAllText($OutputPath, $newContent, [System.Text.UTF8Encoding]::new($false))
Write-Host "Generated MatType constants: $OutputPath"
