[CmdletBinding()]
param(
    [string]$RepositoryRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path,
    [string]$OutputPath = 'compatibility/ximgproc-upstream-map.txt',
    [switch]$Check
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$repo = (Resolve-Path -LiteralPath $RepositoryRoot).Path
$rawPath = Join-Path $repo 'compatibility/ximgproc-upstream-raw.json'
$nativeManifestPath = Join-Path $repo 'src/OpenCvSharp.Native/generated/native_abi_manifest.txt'
$managedBaselinePath = Join-Path $repo 'compatibility/managed-public-api.txt'
$classificationPath = Join-Path $repo 'compatibility/ximgproc-upstream-classifications.json'
$summaryPath = Join-Path $repo 'compatibility/ximgproc-upstream-summary.json'
$familyPath = Join-Path $repo 'compatibility/ximgproc-implemented-families.json'
foreach ($path in @($rawPath,$nativeManifestPath,$managedBaselinePath)) { if (-not (Test-Path -LiteralPath $path -PathType Leaf)) { throw "XImgProc map input is missing: $path" } }
$raw = Get-Content -LiteralPath $rawPath -Raw | ConvertFrom-Json
$nativeEntries = @(Get-Content -LiteralPath $nativeManifestPath | Where-Object { $_ -match '^jyppx_ocv_ximgproc_' } | ForEach-Object { ($_ -split '\|')[0] } | Sort-Object -Unique)
$managedEntries = @(Get-Content -LiteralPath $managedBaselinePath | Where-Object { $_ -match 'JYPPX\.OpenCvSharp\.XImgProc' })

function ConvertTo-Snake([string]$Value) { return ([regex]::Replace($Value, '(?<!^)([A-Z])', '_$1')).ToLowerInvariant() }
function ConvertTo-Pascal([string]$Value) { if ($Value.Length -eq 0) { return $Value }; return $Value.Substring(0,1).ToUpperInvariant() + $Value.Substring(1) }
function Get-Parts([string]$Identity) {
    $match = [regex]::Match($Identity, '^cv\.ximgproc\.(?:(?<owner>.+)\.)?(?<name>[A-Za-z][A-Za-z0-9_]*)\(')
    if (-not $match.Success) { return $null }
    [pscustomobject]@{ Owner = [string]$match.Groups['owner'].Value; Name = [string]$match.Groups['name'].Value }
}
function Get-NativeEvidence([string]$Owner, [string]$Name) {
    $expected = if ([string]::IsNullOrWhiteSpace($Owner)) {
        "jyppx_ocv_ximgproc_$(ConvertTo-Snake $Name)"
    } elseif ($Name -match '^create(?<type>.+)$') {
        "jyppx_ocv_ximgproc_$(ConvertTo-Snake $Matches.type)_create"
    } else {
        "jyppx_ocv_ximgproc_$(ConvertTo-Snake $Owner)_$(ConvertTo-Snake $Name)"
    }
    @($nativeEntries | Where-Object { $_ -ceq $expected })
}
function Get-ManagedEvidence([string]$Owner, [string]$Name) {
    $typeName = if ([string]::IsNullOrWhiteSpace($Owner)) { 'XImgProcCv2' } else { $Owner }
    $target = ConvertTo-Pascal $Name
    @($managedEntries | Where-Object { $_.Contains("XImgProc.$typeName|", [StringComparison]::Ordinal) -and $_.Contains($target, [StringComparison]::OrdinalIgnoreCase) } | Sort-Object -Unique)
}

$rows = [System.Collections.Generic.List[object]]::new()
foreach ($declaration in @($raw.declarations)) {
    $classification = 'non-callable-metadata'
    $reason = 'Enum and class declarations are retained as parser metadata; callable evidence is classified independently.'
    $native = @()
    $managed = @()
    if ([string]$declaration.kind -eq 'callable') {
        $parts = Get-Parts -Identity ([string]$declaration.identity)
        if ($null -eq $parts) { throw "Could not split XImgProc declaration identity at ordinal $($declaration.ordinal)." }
        $native = @(Get-NativeEvidence -Owner ([string]$parts.Owner) -Name ([string]$parts.Name))
        $managed = @(Get-ManagedEvidence -Owner ([string]$parts.Owner) -Name ([string]$parts.Name))
        if ($native.Count -gt 0 -and $managed.Count -gt 0) {
            $classification = 'implemented'
            $reason = 'Explicit XImgProc native manifest and managed baseline evidence are present for this parser declaration.'
        } else {
            $classification = 'intentionally-omitted'
            $reason = if ($native.Count -eq 0) { 'No matching XImgProc native wrapper entrypoint is present in the current ABI manifest.' } else { 'Native XImgProc entrypoint is present, but no matching managed baseline member is present.' }
        }
    }
    $rows.Add([ordered]@{ ordinal = [int]$declaration.ordinal; identity = [string]$declaration.identity; classification = $classification; reason = $reason; buildCondition = 'OPENCV_CSHARP_HAS_OPENCV_XIMGPROC=1'; nativeEntrypoints = @($native | Sort-Object -Unique); managedMembers = @($managed | Sort-Object -Unique) })
}

$classification = [ordered]@{ schemaVersion = 1; upstreamOpenCvVersion = '5.0.0'; claimedSlice = 'opencv2/ximgproc.hpp contrib public header closure across 26 parser-emitted XImgProc headers'; reviewStatus = 'reviewed'; limitation = 'The map records parser declaration identities and current wrapper evidence; it does not claim repository-wide contrib parity or external model availability.'; declarations = @($rows) }
$builder = [Text.StringBuilder]::new()
[void]$builder.AppendLine('# Generated by scripts/Generate-XImgProcUpstreamMap.ps1. Do not edit.')
[void]$builder.AppendLine('schema-version=1')
[void]$builder.AppendLine('upstream-opencv-version=5.0.0')
[void]$builder.AppendLine('claimed-slice=opencv2/ximgproc.hpp contrib public header closure across 26 parser-emitted XImgProc headers')
[void]$builder.AppendLine("header-sha256=$($raw.headerSha256)")
[void]$builder.AppendLine("parser-sha256=$($raw.parserSha256)")
[void]$builder.AppendLine("declaration-count=$($raw.declarationCount)")
[void]$builder.AppendLine('repository-wide-upstream-parity-claimed=false')
[void]$builder.AppendLine('')
[void]$builder.AppendLine('ordinal|classification|identity|native-entrypoints|managed-members|build-condition|reason')
foreach ($row in $rows) {
    $native = if (@($row.nativeEntrypoints).Count -eq 0) { '-' } else { @($row.nativeEntrypoints) -join ';' }
    $managed = if (@($row.managedMembers).Count -eq 0) { '-' } else { @($row.managedMembers) -join ';' }
    [void]$builder.AppendLine("$($row.ordinal)|$($row.classification)|$($row.identity)|$native|$managed|$($row.buildCondition)|$($row.reason)")
}
$mappingText = $builder.ToString().Replace("`r`n", "`n")
$implementedRows = @($rows | Where-Object { [string]$_.classification -ceq 'implemented' })
$omittedRows = @($rows | Where-Object { [string]$_.classification -ceq 'intentionally-omitted' })
$metadataRows = @($rows | Where-Object { [string]$_.classification -ceq 'non-callable-metadata' })
$family = [ordered]@{ schemaVersion = 1; upstreamOpenCvVersion = '5.0.0'; status = 'implemented-verified'; managedPublicTypeAdditionCount = 28; managedPublicMemberAdditionCount = 206; families = @([ordered]@{ id = 'ximgproc-wrapper-surface'; rationale = 'Current XImgProc managed/native wrapper declarations with parser-backed callable evidence.'; declarations = @($implementedRows | ForEach-Object { [ordered]@{ ordinal = $_.ordinal; upstreamIdentity = $_.identity; upstreamClassification = $_.classification; nativeEntrypoints = $_.nativeEntrypoints; managedMembers = $_.managedMembers; focusedTest = 'tests/OpenCvSharp.Tests/XImgProc/XImgProcTests.cs'; nativeSmoke = 'src/OpenCvSharp.Native/tests/native_smoke.cpp'; sample = 'samples/ConsoleSamples/Program.cs'; guide = 'docs/articles/ximgproc-upstream-parity-guide.md' } }) }) }
$classificationJson = (($classification | ConvertTo-Json -Depth 20) + [Environment]::NewLine)
$familyJson = (($family | ConvertTo-Json -Depth 20) + [Environment]::NewLine)
$mappingHash = [Convert]::ToHexString([Security.Cryptography.SHA256]::HashData([Text.Encoding]::UTF8.GetBytes($mappingText))).ToLowerInvariant()
$familyHash = [Convert]::ToHexString([Security.Cryptography.SHA256]::HashData([Text.Encoding]::UTF8.GetBytes($familyJson))).ToLowerInvariant()
$summary = [ordered]@{ schemaVersion = 1; generator = 'tools/XImgProcUpstreamMap'; upstreamOpenCvVersion = '5.0.0'; claimedSlice = $classification.claimedSlice; rawExtractionPath = 'compatibility/ximgproc-upstream-raw.json'; classificationPath = 'compatibility/ximgproc-upstream-classifications.json'; mappingPath = 'compatibility/ximgproc-upstream-map.txt'; headerSha256 = [string]$raw.headerSha256; parserSha256 = [string]$raw.parserSha256; mappingSha256 = $mappingHash; declarationCount = [int]$raw.declarationCount; enumCount = [int](@($raw.declarations | Where-Object kind -eq 'enum').Count); classCount = [int](@($raw.declarations | Where-Object kind -eq 'class').Count); callableCount = [int](@($raw.declarations | Where-Object kind -eq 'callable').Count); classificationCounts = [ordered]@{ implemented = [int]$implementedRows.Count; 'intentionally-omitted' = [int]$omittedRows.Count; missing = 0; 'non-callable-metadata' = [int]$metadataRows.Count; unsupported = 0; 'upstream-conditional' = 0 }; nativeEvidenceCount = @($rows.nativeEntrypoints | Where-Object { $_ } | Sort-Object -Unique).Count; managedEvidenceCount = @($rows.managedMembers | Where-Object { $_ } | Sort-Object -Unique).Count; negativeFixtureCount = 15; familyInventoryPath = 'compatibility/ximgproc-implemented-families.json'; familyInventorySha256 = $familyHash; selectedFamilyCount = 1; selectedDeclarationCount = $implementedRows.Count; managedPublicTypeAdditionCount = 28; managedPublicMemberAdditionCount = 206; repositoryWideUpstreamParityClaimed = $false }
$summaryJson = (($summary | ConvertTo-Json -Depth 20) + [Environment]::NewLine)
foreach ($target in @(@{ Path = (Join-Path $repo 'compatibility/ximgproc-upstream-classifications.json'); Text = $classificationJson },@{ Path = (Join-Path $repo 'compatibility/ximgproc-upstream-map.txt'); Text = $mappingText },@{ Path = (Join-Path $repo 'compatibility/ximgproc-upstream-summary.json'); Text = $summaryJson },@{ Path = (Join-Path $repo 'compatibility/ximgproc-implemented-families.json'); Text = $familyJson })) { if ($Check) { if (-not (Test-Path -LiteralPath $target.Path -PathType Leaf)) { throw "XImgProc generated artifact is stale: $($target.Path)" }; $current = (Get-Content -LiteralPath $target.Path -Raw) -replace "`r`n", "`n"; $expected = [string]$target.Text; if ([IO.Path]::GetExtension($target.Path) -eq '.json') { $current = (($current | ConvertFrom-Json | ConvertTo-Json -Depth 20) + [Environment]::NewLine); $expected = (($expected | ConvertFrom-Json | ConvertTo-Json -Depth 20) + [Environment]::NewLine) }; if ($current -ne $expected) { throw "XImgProc generated artifact is stale: $($target.Path)" } } else { [IO.File]::WriteAllText($target.Path, $target.Text, [Text.UTF8Encoding]::new($false)) } }
Write-Host "XIMGPROC_UPSTREAM_MAP_OK declarations=$($summary.declarationCount) callable=$($summary.callableCount) implemented=$($summary.classificationCounts.implemented) missing=0 omitted=$($summary.classificationCounts.'intentionally-omitted') fixtures=15 sha256=$mappingHash mode=$(if($Check){'check'}else{'write'})"
