param([string]$RepositoryRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')))
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop'
$repo=(Resolve-Path -LiteralPath $RepositoryRoot).Path
& (Join-Path $PSScriptRoot 'Generate-BgSegmUpstreamMap.ps1') -RepositoryRoot $repo -Check
if(-not $?){throw 'BgSegm upstream map freshness validation failed.'}
$s=Get-Content (Join-Path $repo 'compatibility/bgsegm-upstream-summary.json') -Raw|ConvertFrom-Json
$classes=Get-Content (Join-Path $repo 'compatibility/bgsegm-upstream-classifications.json') -Raw|ConvertFrom-Json
$native=@(Get-Content (Join-Path $repo 'src/OpenCvSharp.Native/generated/native_abi_manifest.txt')|Where-Object {$_ -match '^jyppx_ocv_bgsegm_'}|ForEach-Object {($_ -split '\|')[0]})
if([int]$s.classificationCounts.missing -ne 0 -or [int]$s.declarationCount -ne 66 -or [int]$s.classificationCounts.implemented -ne 50 -or [int]$s.classificationCounts.'intentionally-omitted' -ne 8){throw 'BgSegm upstream map partition drifted.'}
foreach($row in @($classes.declarations|Where-Object classification -eq 'implemented')){foreach($entry in @($row.nativeEntrypoints)){if($native -notcontains [string]$entry){throw "BgSegm implemented row references an unknown native entrypoint: $entry"}}}
$falseBase=@($classes.declarations|Where-Object {$_.classification -eq 'implemented' -and $_.identity -match 'BackgroundSubtractor(MOG|GMG|CNT)\.(apply|getBackgroundImage)' -and (@($_.managedMembers|Where-Object {$_ -match 'BgSegmBackgroundSubtractor' -and $_ -notmatch 'ValidateApplyImage'}).Count -eq 0)})
if($falseBase.Count -gt 0){throw 'BgSegm inherited methods lost their base-class evidence.'}
foreach($expected in @(@{identity='cv.bgsegm.BackgroundSubtractorMOG.apply(Mat image;Mat fgmask';native='jyppx_ocv_bgsegm_background_subtractor_apply'},@{identity='cv.bgsegm.BackgroundSubtractorMOG.apply(Mat image;Mat knownForegroundMask';native='jyppx_ocv_bgsegm_background_subtractor_apply_with_known_foreground'},@{identity='cv.bgsegm.createBackgroundSubtractorGMG(';native='jyppx_ocv_bgsegm_background_subtractor_gmg_create'},@{identity='cv.bgsegm.SyntheticSequenceGenerator.getNextFrame(';native='jyppx_ocv_bgsegm_synthetic_sequence_generator_get_next_frame'})){ $row=@($classes.declarations|Where-Object {$_.identity.StartsWith($expected.identity)}); if($row.Count -ne 1 -or @($row[0].nativeEntrypoints) -notcontains $expected.native -or @($row[0].managedMembers).Count -eq 0){throw "BgSegm declaration-to-symbol evidence drifted: $($expected.identity)"} }
$gsocLsbpRows=@($classes.declarations|Where-Object {$_.identity -match '^cv\.bgsegm\.(?:BackgroundSubtractorGSOC|BackgroundSubtractorLSBP)\.|^cv\.bgsegm\.createBackgroundSubtractor(?:GSOC|LSBP)\('})
if($gsocLsbpRows.Count -ne 8 -or @($gsocLsbpRows|Where-Object {$_.classification -ne 'intentionally-omitted' -or @($_.nativeEntrypoints).Count -ne 0 -or @($_.managedMembers).Count -ne 0 -or [string]$_.reason -notmatch 'optional|GSOC|LSBP|ownership|lifetime|runtime smoke'}).Count -ne 0){throw 'BgSegm GSOC/LSBP omission evidence drifted.'}
Write-Host "BGSEGM_UPSTREAM_MAP_CONTRACT_OK declarations=$($s.declarationCount) callables=$($s.callableCount) implemented=$($s.classificationCounts.implemented) omitted=$($s.classificationCounts.'intentionally-omitted') missing=0 fixtures=$($s.negativeFixtureCount) nativeEvidence=$($s.nativeEvidenceCount) sha256=$($s.mappingSha256)"
