param([string]$RepositoryRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')))
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop'
$repo=(Resolve-Path -LiteralPath $RepositoryRoot).Path
& (Join-Path $PSScriptRoot 'Generate-LineDescriptorUpstreamMap.ps1') -RepositoryRoot $repo -Check
$summary=Get-Content (Join-Path $repo 'compatibility/line_descriptor-upstream-summary.json') -Raw|ConvertFrom-Json
$map=Get-Content (Join-Path $repo 'compatibility/line_descriptor-upstream-classifications.json') -Raw|ConvertFrom-Json
$manifest=@(Get-Content (Join-Path $repo 'src/OpenCvSharp.Native/generated/native_abi_manifest.txt')|ForEach-Object {($_ -split '\|')[0]})
if([int]$summary.declarationCount -ne 34 -or [int]$summary.callableCount -ne 28 -or [int]$summary.classificationCounts.implemented -ne 14 -or [int]$summary.classificationCounts.'intentionally-omitted' -ne 14 -or [int]$summary.classificationCounts.missing -ne 0){throw 'LineDescriptor upstream map partition drifted.'}
$matcher=@($map.declarations|Where-Object {$_.identity.StartsWith('cv.line_descriptor.BinaryDescriptorMatcher.match(Mat queryDescriptors') -and $_.identity -match 'Mat trainDescriptors'});if($matcher.Count -ne 1 -or $matcher[0].classification -ne 'implemented' -or @($matcher[0].nativeEntrypoints) -notcontains 'jyppx_ocv_line_descriptor_binary_descriptor_matcher_match_count' -or @($matcher[0].nativeEntrypoints) -notcontains 'jyppx_ocv_line_descriptor_binary_descriptor_matcher_match_fill'){throw 'LineDescriptor exact Matcher.Match mapping drifted.'};if(@($matcher[0].managedMembers|Where-Object {$_ -match '\.KnnMatch\('}).Count -ne 0){throw 'LineDescriptor Match was cross-bound to KnnMatch.'}
$constructor=@($map.declarations|Where-Object {$_.identity.StartsWith('cv.line_descriptor.BinaryDescriptorMatcher.BinaryDescriptorMatcher(')});if($constructor.Count -ne 1 -or $constructor[0].classification -ne 'implemented' -or @($constructor[0].nativeEntrypoints) -notcontains 'jyppx_ocv_line_descriptor_binary_descriptor_matcher_create'){throw 'LineDescriptor matcher construction evidence drifted.'}
$keyLine=@($map.declarations|Where-Object {$_.identity.StartsWith('cv.line_descriptor.KeyLine.getStartPoint(')});if($keyLine.Count -ne 1 -or $keyLine[0].classification -ne 'intentionally-omitted' -or @($keyLine[0].managedMembers).Count -ne 1 -or [string]$keyLine[0].reason -notmatch 'no separate native wrapper entrypoint'){throw 'LineDescriptor managed-only KeyLine accessor boundary drifted.'}
foreach($entry in @('jyppx_ocv_line_descriptor_binary_descriptor_matcher_create','jyppx_ocv_line_descriptor_binary_descriptor_matcher_match_count','jyppx_ocv_line_descriptor_binary_descriptor_matcher_match_fill')){if($manifest -notcontains $entry){throw "LineDescriptor native ABI entrypoint is missing: $entry"}}
Write-Host "LINE_DESCRIPTOR_UPSTREAM_MAP_CONTRACT_OK declarations=$($summary.declarationCount) callables=$($summary.callableCount) implemented=$($summary.classificationCounts.implemented) omitted=$($summary.classificationCounts.'intentionally-omitted') missing=0 sha256=$($summary.mappingSha256)"
